services:
  - type: web
    name: property-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
      libcairo2 \
      libpango-1.0-0 \
      libpangocairo-1.0-0 \
      libgdk-pixbuf2.0-0 \
      libffi-dev \
      shared-mime-info
      pip install -r requirements.txt
    startCommand: uvicorn app.web:app --host 0.0.0.0 --port $PORT